# Shell variables
# Generated by 'wal'
wallpaper='/home/ahmed/backdrops/screen-0.jpg'

# Special
background='#0A0607'
foreground='#c7c7c4'
cursor='#c7c7c4'

# Colors
color0='#0A0607'
color1='#499E4E'
color2='#9F8F69'
color3='#D79E4B'
color4='#346A9F'
color5='#CE6590'
color6='#519EB7'
color7='#c7c7c4'
color8='#8b8b89'
color9='#499E4E'
color10='#9F8F69'
color11='#D79E4B'
color12='#346A9F'
color13='#CE6590'
color14='#519EB7'
color15='#c7c7c4'

# FZF colors
export FZF_DEFAULT_OPTS="
    $FZF_DEFAULT_OPTS
    --color fg:7,bg:0,hl:1,fg+:232,bg+:1,hl+:255
    --color info:7,prompt:2,spinner:1,pointer:232,marker:1
"

# Fix LS_COLORS being unreadable.
export LS_COLORS="${LS_COLORS}:su=30;41:ow=30;42:st=30;44:"
