--Place this file in your .xmonad/lib directory and import module Colors into .xmonad/xmonad.hs config
--The easy way is to create a soft link from this file to the file in .xmonad/lib using ln -s
--Then recompile and restart xmonad.

module Colors
    ( wallpaper
    , background, foreground, cursor
    , color0, color1, color2, color3, color4, color5, color6, color7
    , color8, color9, color10, color11, color12, color13, color14, color15
    ) where

-- Shell variables
-- Generated by 'wal'
wallpaper="/home/ahmed/backdrops/screen-0.jpg"

-- Special
background="#0A0607"
foreground="#c7c7c4"
cursor="#c7c7c4"

-- Colors
color0="#0A0607"
color1="#499E4E"
color2="#9F8F69"
color3="#D79E4B"
color4="#346A9F"
color5="#CE6590"
color6="#519EB7"
color7="#c7c7c4"
color8="#8b8b89"
color9="#499E4E"
color10="#9F8F69"
color11="#D79E4B"
color12="#346A9F"
color13="#CE6590"
color14="#519EB7"
color15="#c7c7c4"
