--Place this file in your .xmonad/lib directory and import module Colors into .xmonad/xmonad.hs config
--The easy way is to create a soft link from this file to the file in .xmonad/lib using ln -s
--Then recompile and restart xmonad.

module Colors
    ( wallpaper
    , background, foreground, cursor
    , color0, color1, color2, color3, color4, color5, color6, color7
    , color8, color9, color10, color11, color12, color13, color14, color15
    ) where

-- Shell variables
-- Generated by 'wal'
wallpaper="/home/ahmed/Downloads/7c32942a6bc1c1e1104d58ecafa27437.jpg"

-- Special
background="#090302"
foreground="#e1c890"
cursor="#e1c890"

-- Colors
color0="#090302"
color1="#5C3E4B"
color2="#8F5008"
color3="#9F610D"
color4="#AF670D"
color5="#AD6E08"
color6="#D2991B"
color7="#e1c890"
color8="#9d8c64"
color9="#5C3E4B"
color10="#8F5008"
color11="#9F610D"
color12="#AF670D"
color13="#AD6E08"
color14="#D2991B"
color15="#e1c890"
